### ISSUE TITLE
Include git?

### ISSUE THREAD

**Issue by ryanvgates** [JonCubed/docker-jenkins-jnlp-slave-windows#1]
Does this docker image include an installation of git? 

I have a build that I'm running from jenkins on a running container and its failing. I'm trying to figure out if git is not installed or just not in the path.

**Comment by JonCubed** [comment]
this version doesn't, but I do have one with it. I'll try update the dockerfile tonight with my latest.

**Comment by JonCubed** [comment]
updated to include git and push a new image to https://hub.docker.com/r/jonathank/jenkins-jnlp-slave-windows/

**Comment by ryanvgates** [comment]
Thank you for making that update. I'll test it tomorrow and let you know how it goes.

**Comment by JonCubed** [comment]
np, thanks
