### ISSUE TITLE
Update git and jenkins versions

### ISSUE THREAD

**Issue by goranbrkic** [JonCubed/docker-jenkins-jnlp-slave-windows#7]
As image is almost a year old it makes sense to update git and jenkins components.

**Comment by goranbrkic** [comment]
https://github.com/JonCubed/docker-jenkins-jnlp-slave-windows/pull/6

**Comment by goranbrkic** [comment]
@JonCubed take a look at https://github.com/JonCubed/docker-jenkins-jnlp-slave-windows/pull/6

**Comment by JonCubed** [comment]
Thanks @goranbrkic for the update. PR has been merged I'll push a new version soon

**Comment by JonCubed** [comment]
This is now available by the following tags `latest` & `remoting-3.23`
